DATA_ACQUISITON:
  DATA_PATH: "../../data/raw"
  START_DATE: "2022-01-03"
  END_DATE: "2025-11-21"

DATA_PREP:
  PROCESSED_PATH: "../../data/processed"
  TRAIN_DATE: "2023-12-31"
  VALIDATION_DATE: "2024-06-30"
  TEST_DATE: "2024-11-21"
